/**
 * A2A message definitions for Agent Notary.
 *
 * Note: no dual-nonce model. A single sharedNonce is generated by
 * the submitter and communicated in the propose message. Both parties use
 * it when calling computeOutcomeHash. Anti-replay is sufficient with one
 * nonce — a confirmerNonce adds complexity without security benefit.
 * Also, outcomeSalt is included to the propose message. The submitter generates
 * a high-entropy salt and includes it here. The confirmer must include this
 * same salt in their outcomeData before hashing. This prevents brute-force
 * reversal of low-entropy payloads (e.g. {"status":"ok"}).
 */

// ── Step 1: Submitter → Confirmer ─────────────────────────────────────────

export interface NotaryPropose {
  type: "notary/propose";
  version: "1.0";
  /** UUID v4 — unique identifier for this interaction. */
  interactionId: string;
  submitterAddress: string;
  confirmerAddress: string;
  /**
   * Schema of the outcomeData field. Both parties must produce identical
   * JSON serialization when hashing. Key ordering matters.
   * Example: "jobId:string,status:string,completedAt:number,_salt:string"
   */
  outcomeDataSchema: string;
  /** Unix timestamp both parties will use in computeOutcomeHash. */
  agreedTimestamp: number;
  expirationHours: number;
  /**
   * Single shared nonce (replaces submitterNonce + confirmerNonce).
   * Generated by submitter with freshNonce(). Both parties pass this to
   * computeOutcomeHash. Anti-replay is enforced on-chain by marking this
   * nonce as used in the slot storage.
   */
  sharedNonce: string;
  /**
   * High-entropy salt to prevent brute-force hash reversal.
   * Generated by submitter with freshSalt(). Must be included in outcomeData
   * under the key "_salt" by both parties before hashing.
   * Example outcomeData: { jobId: "abc", status: "ok", _salt: "<this value>" }
   */
  outcomeSalt: string;
  chainId: number;
}

// ── Step 2a: Confirmer → Submitter (acceptance) ───────────────────────────

export interface NotaryAcknowledge {
  type: "notary/acknowledge";
  version: "1.0";
  interactionId: string;
  confirmerAddress: string;
  /** Must echo agreedTimestamp from the propose message exactly. */
  acceptedTimestamp: number;
  /**
   * Note: no confirmerNonce. The single sharedNonce from the
   * propose message is sufficient. Both parties now produce the same
   * hash using the same nonce.
   */
}

// ── Step 2b: Confirmer → Submitter (off-chain fast decline) ──────────────

export interface NotaryDecline {
  type: "notary/decline";
  version: "1.0";
  interactionId: string;
  confirmerAddress: string;
  /** Optional. Not stored on-chain. */
  reason?: string;
}

// ── Step 3: Query ─────────────────────────────────────────────────────────

export interface NotaryQuery {
  type: "notary/query";
  interactionId: string;
  requesterAddress: string;
}

export interface NotaryResult {
  type: "notary/result";
  interactionId: string;
  state:
    | "PENDING"
    | "WITNESSED"
    | "FAILED"
    | "DISPUTED"
    | "DECLINED"
    | "EXPIRED"
    | "NOT_FOUND";
  easUID?:    string;
  timestamp?: number;
}

// ── Union type ─────────────────────────────────────────────────────────────

export type NotaryMessage =
  | NotaryPropose
  | NotaryAcknowledge
  | NotaryDecline
  | NotaryQuery
  | NotaryResult;

// ── Validation helpers ─────────────────────────────────────────────────────

export function validateAcknowledge(
  proposal: NotaryPropose,
  ack: NotaryAcknowledge
): { valid: boolean; error?: string } {
  if (ack.interactionId !== proposal.interactionId)
    return { valid: false, error: "interactionId mismatch" };
  if (ack.confirmerAddress !== proposal.confirmerAddress)
    return { valid: false, error: "confirmerAddress mismatch" };
  if (ack.acceptedTimestamp !== proposal.agreedTimestamp)
    return { valid: false, error: "timestamp mismatch" };
  return { valid: true };
}
