/**
 * AgentNotary SDK.
 *
 * Primary integration surface for AI agents.
 * Import this class, instantiate with your RPC URL and private key,
 * and use it to submit hashes, query slot states, and check agent statuses.
 *
 * Usage:
 *   import { AgentNotary } from "./AgentNotary";
 *   const notary = new AgentNotary(process.env.SEPOLIA_URL!, process.env.PRIVATE_KEY!);
 *   const status = await notary.getAgentStatus("0xABC...");
 */

import { ethers } from "ethers";
import * as crypto from "crypto";
import stableStringify from "json-stable-stringify";

// ── ABIs ──────────────────────────────────────────────────────────────────

const NOTARY_ABI = [
  "function computeHash(bytes32,bytes,uint64,address,address,uint8,bytes32) view returns (bytes32)",
  "function submitHash(bytes32,bytes32,uint8,address,uint32,bytes32,uint256) external",
  "function confirmHash(bytes32,bytes32,uint8,address,bytes32,uint256) external",
  "function markExpired(bytes32) external",
  "function slots(bytes32) view returns (bytes32,uint8,address,address,uint64,uint8,bool,uint256,uint256,bytes32)",
  "event WitnessedAttestation(bytes32 indexed,address indexed,address indexed,bytes32,uint256,uint16,bytes32)",
  "event FailureAttestation(bytes32 indexed,address indexed,address indexed,uint256,uint16,bytes32)",
  "event Disputed(bytes32 indexed,address,address,bytes32,uint8,bytes32,uint8)",
  "event Declined(bytes32 indexed,address indexed)",
];

const FEE_REGISTRY_ABI = [
  "function minFee() view returns (uint256)",
  "function balances(address) view returns (uint256)",
  "function escrowedFees() view returns (uint256)",
  "function withdrawableFees() view returns (uint256)",
  "function totalBurned() view returns (uint256)",
  "function deposit(uint256) external",
  "function agentWithdraw(uint256) external",
  "function setMinFee(uint256) external",
];

const USDC_ABI = [
  "function approve(address,uint256) external returns (bool)",
  "function allowance(address,address) view returns (uint256)",
  "function balanceOf(address) view returns (uint256)",
];

// ── Types ─────────────────────────────────────────────────────────────────

export type AgentStatus = "Active" | "Established" | "Verified" | "Suspicious" | "Unknown";

export interface DeployedAddresses {
  notaryCore:         string;
  feeRegistry:        string;
  usdcAddress:        string;
  witnessedSchemaUID: string;
  failureSchemaUID:   string;
}

export interface SubmissionParams {
  /** Shared interaction identifier — UUID v4 agreed off-chain. Must be bytes32 hex. */
  interactionId:    string;   // bytes32 hex
  /** Application-specific outcome payload. Will be JSON-stringified before hashing. */
  outcomeData:      object;   // MUST include a random salt field — see below
  agreedTimestamp:  number;   // unix — agreed with counterparty in A2A propose
  counterparty:     string;   // address
  /**
  * Expiration window in hours. Only used on the first (submitter) submission.
  * Pass 0 on the confirmer side.
  */
  expirationHours:  number;
    /** Outcome signal: 1=ACCEPTED, 2=CANCELLED (confirmer only), 3=FAILURE */
  outcome:          1 | 2 | 3;
  sharedNonce:      string;   // bytes32 hex — generated by submitter, shared in A2A propose
  depositAmount:    bigint;   // USDC units (6 decimals)
}

export interface SlotState {
  submitter:  string;
  confirmer:  string;
  expiresAt:  number;
  state: "PENDING" | "WITNESSED" | "FAILED" | "DISPUTED" | "DECLINED" | "EXPIRED" | "UNKNOWN";
}

// ── Hash helpers ──────────────────────────────────────────────────────────

/**
 * Compute the outcome match hash.
 *
 * Key decisions:
 * - Addresses are sorted (lower < higher) before hashing.
 * Both parties produce the same hash regardless of submission order.
 *
 * - outcomeData MUST contain a high-entropy salt. The SDK enforces
 * this by injecting one automatically if not present. Example payload:
 *   { jobId: "abc", result: "ok", _salt: "a3f9..." }
 * The salt is communicated between parties in the A2A acknowledge message
 * alongside the sharedNonce and is never posted to the chain separately.
 *
 * - Outcome byte is included in the pre-image. A party cannot submit
 * outcome=ACCEPTED while their hash encodes a failure state.
 *
 * - json-stable-stringify is used instead of JSON.stringify. Standard
 * JSON.stringify does not guarantee property order across JS engines, and
 * agents on different runtimes (Python, Rust, browser) produce different byte
 * sequences for the same object. stableStringify sorts keys alphabetically,
 * making serialisation deterministic across all runtimes.
 *
 * - Returns both the hash and the salt actually used, so callers can share
 * the salt with the confirmer via the A2A propose message.
 */
export function computeOutcomeHash(
  interactionId: string,
  outcomeData:   object,
  timestamp:     number,
  addrA:         string,
  addrB:         string,
  outcome:       number,
  sharedNonce:   string
): { hash: string; salt: string } {
  const [first, second] = addrA.toLowerCase() < addrB.toLowerCase()
    ? [addrA, addrB]
    : [addrB, addrA];

  const salt = (outcomeData as any)._salt ?? crypto.randomBytes(32).toString("hex");
  const dataWithSalt = { ...outcomeData, _salt: salt };

  const dataBytes = ethers.toUtf8Bytes(stableStringify(dataWithSalt) as string);

  const hash = ethers.keccak256(ethers.AbiCoder.defaultAbiCoder().encode(
    ["bytes32", "bytes", "uint64", "address", "address", "uint8", "bytes32"],
    [interactionId, dataBytes, timestamp, first, second, outcome, sharedNonce]
  ));

  return { hash, salt };
}

/**
 * Generate a fresh shared nonce. Called by the submitter once per interaction.
 * Communicated to the confirmer in the A2A notary/propose message.
 * Both parties use this same nonce when calling computeOutcomeHash. *
 */
export function freshNonce(): string {
  return ethers.hexlify(ethers.randomBytes(32));
}

/**
 * Generate a high-entropy outcome salt.
 * The submitter generates this, includes it in the A2A propose message,
 * and both parties include it in their outcomeData before hashing.
 */
export function freshSalt(): string {
  return crypto.randomBytes(32).toString("hex");
}

// ── Main SDK class ────────────────────────────────────────────────────────

export class AgentNotary {
  private notaryCore:   ethers.Contract;
  private feeRegistry:  ethers.Contract;
  private usdc:         ethers.Contract;
  private signer:       ethers.Signer;
  private addresses:    DeployedAddresses;
  private easGraphQL:   string;

  constructor(
    rpcUrl:    string,
    privateKey: string,
    addresses: DeployedAddresses,
    easGraphQL = "https://base.easscan.org/graphql"  // update per chain
  ) {
    const provider    = new ethers.JsonRpcProvider(rpcUrl);
    this.signer       = new ethers.Wallet(privateKey, provider);
    this.addresses    = addresses;
    this.easGraphQL   = easGraphQL;
    this.notaryCore   = new ethers.Contract(addresses.notaryCore,   NOTARY_ABI,       this.signer);
    this.feeRegistry  = new ethers.Contract(addresses.feeRegistry,  FEE_REGISTRY_ABI, this.signer);
    this.usdc         = new ethers.Contract(addresses.usdcAddress,  USDC_ABI,         this.signer);
  }

  // ── Submission ──────────────────────────────────────────────────────────

  /**
   * Deposit USDC credit for future fee payments (Option B fair credit).
   * Approve the FeeRegistry first.
   */
  async deposit(usdcAmount: bigint): Promise<string> {
    const approveTx = await this.usdc.approve(this.addresses.feeRegistry, usdcAmount);
    await approveTx.wait();
    const tx = await this.feeRegistry.deposit(usdcAmount);
    const receipt = await tx.wait();
    return receipt.hash;
  }

  /**
   * Withdraw unused credit balance.
   */
  async agentWithdraw(usdcAmount: bigint): Promise<string> {
    const tx = await this.feeRegistry.agentWithdraw(usdcAmount);
    const receipt = await tx.wait();
    return receipt.hash;
  }

  /** Check this agent's current credit balance. */
  async creditBalance(): Promise<bigint> {
    const addr = await this.signer.getAddress();
    return this.feeRegistry.balances(addr);
  }

  /**
   * Submit the first hash (submitter side).
   */
  async submitHash(params: SubmissionParams): Promise<{ txHash: string; salt: string }> {
    const signerAddr = await this.signer.getAddress();

    const { hash, salt } = computeOutcomeHash(
      params.interactionId,
      params.outcomeData,
      params.agreedTimestamp,
      signerAddr,
      params.counterparty,
      params.outcome,
      params.sharedNonce
    );

    const tx = await this.notaryCore.submitHash(
      params.interactionId,
      hash,
      params.outcome,
      params.counterparty,
      params.expirationHours,
      params.sharedNonce,
      params.depositAmount
    );
    const receipt = await tx.wait();
    return { txHash: receipt.hash, salt };
  }

  /**
   * Confirm a slot (confirmer side).
   * Requires the shared nonce and outcomeData communicated via A2A.
   */
  async confirmHash(
    interactionId:   string,
    outcomeData:     object,
    agreedTimestamp: number,
    submitter:       string,
    outcome:         1 | 2 | 3,
    sharedNonce:     string,
    depositAmount:   bigint
  ): Promise<string> {
    const signerAddr = await this.signer.getAddress();

    const { hash } = computeOutcomeHash(
      interactionId,
      outcomeData,
      agreedTimestamp,
      submitter,
      signerAddr,
      outcome,
      sharedNonce
    );

    const tx = await this.notaryCore.confirmHash(
      interactionId,
      hash,
      outcome,
      submitter,   
      sharedNonce,
      depositAmount
    );
    const receipt = await tx.wait();
    return receipt.hash;
  }

  // ── Query ───────────────────────────────────────────────────────────────

  /** Read slot state from chain. */
  async getSlot(interactionId: string): Promise<SlotState> {
    const s = await this.notaryCore.slots(interactionId);
    const STATES = ["PENDING","WITNESSED","FAILED","DISPUTED","DECLINED","EXPIRED"];
    return {
      submitter: s[2],
      confirmer: s[3],
      expiresAt: Number(s[4]),
      state: (STATES[Number(s[5])] ?? "UNKNOWN") as SlotState["state"],
    };
  }

  /**
   * Get agent status.
   *
   *- Witnessed badges: queried by recipient field on the Witnessed schema.
   *   NOTE: For full accuracy, query both submitter and confirmer roles via
   *   a subgraph that indexes both addresses. EAScan supports filtering by
   *   attester (NotaryCore) and the data fields if you deploy a custom subgraph.
   *   The recipient field alone captures confirmer role; submitter role requires
   *   the subgraph approach described in indexer.ts.
   * It uses EAS subgraph with proper indexed field filtering instead of
   * fetching 10,000 attestations and scanning hex blobs client-side.
   * Witnessed badge query is paginated. Previously the hard
   * take: 10000 cap caused inaccurate status ratings for high-volume agents
   * once their interaction count exceeded the limit. Pagination continues
   * fetching until all pages are exhausted.
   *
   * - Witnessed badges: paginated, filtered by attester (NotaryCore) and
   *   schema, then client-filtered by address in decodedDataJson. For full
   *   accuracy at scale deploy the custom subgraph (see indexer.ts) which
   *   indexes both submitter and confirmer as separate indexed fields.
   *
   * - Failure badges: recipient = failingParty (set explicitly in the contract).
   *   These are fully indexed and accurate without a custom subgraph.
   */

   /**
   * Derive the agent status for a given address from EAS attestation data.
   * Status is computed entirely from on-chain facts — no trusted authority.
   *
   * Priority order (first match wins):
   *   Suspicious  → >50% of interactions ended in failure
   *   Verified    → 10,000+ witnessed AND success rate ≥ 80%
   *   Established → 100+ witnessed AND success rate ≥ 80%
   *   Active      → 1+ witnessed in the last 30 days
   *   Unknown     → none of the above
   */
  async getAgentStatus(agentAddress: string): Promise<{
    status: AgentStatus;
    witnessed: number;
    failures: number;
    successRate: number;
  }> {
    const addr = agentAddress.toLowerCase();
    const PAGE_SIZE = 1000;

    const allWitnessed: any[] = [];
    let skip = 0;
    while (true) {
      const result = await this._graphQuery(`{
        attestations(
          where: {
            schemaId: { equals: "${this.addresses.witnessedSchemaUID}" },
            attester: { equals: "${this.addresses.notaryCore}" }
          }
          orderBy: { timeCreated: asc }
          take: ${PAGE_SIZE}
          skip: ${skip}
        ) {
          id
          timeCreated
          decodedDataJson
        }
      }`);
      const page: any[] = result?.data?.attestations ?? [];
      allWitnessed.push(...page);
      if (page.length < PAGE_SIZE) break;  // last page
      skip += PAGE_SIZE;
    }

    // Filter to those involving this agent (submitter or confirmer).
    // Decoded data includes both addresses — parse them from decodedDataJson.
    const agentWitnessed = allWitnessed.filter(a => {
      try {
        const decoded = JSON.parse(a.decodedDataJson ?? "[]");
        return decoded.some((field: any) =>
          field.value?.value?.toLowerCase() === addr
        );
      } catch { return false; }
    });

    // Failure badges: recipient field is indexed — no pagination needed for
    // most agents since failures are relatively rare. Paginate if needed.
    const failureResult = await this._graphQuery(`{
      attestations(
        where: {
          schemaId: { equals: "${this.addresses.failureSchemaUID}" },
          attester: { equals: "${this.addresses.notaryCore}" },
          recipient: { equals: "${agentAddress}" }
        }
        take: ${PAGE_SIZE}
      ) { id timeCreated }
    }`);
    const failures: any[] = failureResult?.data?.attestations ?? [];

    const now           = Math.floor(Date.now() / 1000);
    const thirtyDaysAgo = now - 30 * 24 * 3600;
    const recentCount   = agentWitnessed.filter(a => a.timeCreated >= thirtyDaysAgo).length;

    const total       = agentWitnessed.length + failures.length;
    const successRate = total > 0 ? agentWitnessed.length / total : 0;

    let status: AgentStatus;
    if (total > 0 && failures.length / total > 0.5)               status = "Suspicious";
    else if (agentWitnessed.length >= 10_000 && successRate >= 0.8) status = "Verified";
    else if (agentWitnessed.length >= 100   && successRate >= 0.8)  status = "Established";
    else if (recentCount >= 1)                                       status = "Active";
    else                                                             status = "Unknown";

    return {
      status,
      witnessed: agentWitnessed.length,
      failures:  failures.length,
      successRate,
    };
  }

  private async _graphQuery(query: string): Promise<any> {
    const res = await fetch(this.easGraphQL, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ query }),
    });
    return res.json();
  }
}
